# Generated by Django 4.1.5 on 2023-02-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Share your experience'),
        ),
        migrations.AlterField(
            model_name='replay_comment',
            name='text',
            field=models.TextField(verbose_name='Replay'),
        ),
    ]
